services:
  service_app:
    build: ./services/app
    ports:
      - "4002:4002"
  service_user:
    build: ./services/user
    ports:
      - "4001:4001"
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:4000"
    environment:
      - APP_SERVICE_URL=http://service_app:4002
      - USER_SERVICE_URL=http://service_user:4001
