services:
  app-service:
    build: ./services/app
    container_name: app-service
    ports:
      - "4002:4002"
  user-service:
    build: ./services/user
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=${MONGO_DB_URL}
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    environment:
      - APP_SERVICE_URL=http://app-service:4002
      - USER_SERVICE_URL=http://user-service:4001
