services:
  app_service:
    build: ./services/app
    ports:
      - "4002:4002"
  user_service:
    build: ./services/user
    ports:
      - "4001:4001"
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:4000"
    environment:
      - APP_SERVICE_URL=http://app_service:4002
      - USER_SERVICE_URL=http://user_service:4001
