services:
  app:
    build: ./services/app
    container_name: app-services
    ports:
      - "4002:4002"
  user:
    build: ./services/user
    container_name: user-services
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=${MONGO_DB_URL}
    # - DATABASE_URL=https://mongodb+srv://username:docker-compose
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    environment:
      - APP_SERVICE_URL=http://app:4002
      - USER_SERVICE_URL=http://user:4001
